# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  skip: true
checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
release:
  github:
    owner: henworth
    name: tflint-ruleset-basic-ext
snapshot:
  name_template: "{{ .Tag }}-dev"
