name: e2e
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 #v4.0.0
        name: Setup TFLint
        with:
          tflint_version: v0.50.3
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #v5.0.2
        with:
          go-version: 1.22
      - name: Run install
        run: make install
      - name: Run e2e tests
        run: make e2e