name: e2e
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #v4.1.3
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 #v4.0.0
        name: Setup TFLint
        with:
          tflint_version: v0.50.3
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version: 1.22
      - name: Run install
        run: make install
      - name: Run e2e tests
        run: make e2e